// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qagrkfveezgdjgmziabn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZ3JrZnZlZXpnZGpnbXppYWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTc4MDMsImV4cCI6MjA3MDU3MzgwM30.pca5RuUDdnk3oIhe_6wML47E4WRWBxpSd7Iri9nHIp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});